import type { Metadata } from "next";
import { Geist, Geist_Mono, Preahvihear } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../Redux/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const preah = Preahvihear({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Ali Mostafa",
  description: "Generated by Ali Mostafa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${preah.className} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
